server:
  port: 9000
  servlet:
    context-path: /email-service

spring:
  application:
    name: email-service


  mail:
    host: smtp.gmail.com
    port: 465
    username: vietddls06@gmail.com
    password: loeavfbmttsgqnlu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

